# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    form:
        csrf_protection:
            enabled: true
            
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
when@dev:
    framework:
        form:
            csrf_protection:
                # CSRF protection is intentionally disabled in dev for easier testing; do not disable in production!
                enabled: false
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
