services:
  ###> doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app_network
  ###< symfony/mailer ###

  ##> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongo:6.0
    command: ["mongod", "--noauth"]   # Disable authentication  # Change in production
    ports:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: EcoRide
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  ##< doctrine/mongodb-odm-bundle ###

volumes:
  database_data:
  mongodb_data:
